server:
  port: 8081
spring:
  profiles:
    active: prod
  application:
    name: address-book
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
    root: ERROR
    com.capgemini.address_book.controller: INFO
    file:
     name: logs/application.log
    pattern:
     console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n"
     file:  "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"





